language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
notifications:
  email: false

before_install:
  - sudo wget https://apt.repos.intel.com/setup/intelproducts.list -O /etc/apt/sources.list.d/intelproducts.list
  - sudo apt-get update
  - sudo apt-get --allow-unauthenticated -y install intel-mkl-2019.1-053 libgomp1
  - export MKLROOT=/opt/intel/compilers_and_libraries/linux/mkl
  - export MKLVARS_ARCHITECTURE=intel64
  - source $MKLROOT/bin/mklvars.sh
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgomp.so.1 /usr/lib/x86_64-linux-gnu/libgomp.so
  
